export const headCells = [
  {
    id: "username",
    align: "left",
    icon: false,
    date: false,
    numeric: false,
    disablePadding: true,
    label: "Username / Names",
  },
  {
    id: "email",
    align: "left",
    icon: false,
    date: false,
    numeric: false,
    disablePadding: false,
    label: "Email",
  },
  {
    id: "levelAuth",
    align: "left",
    icon: false,
    date: false,
    numeric: false,
    disablePadding: false,
    label: "Position",
  },
  {
    id: "lastLogin",
    align: "right",
    icon: false,
    date: true,
    numeric: false,
    disablePadding: false,
    label: "Last Login",
  },
  {
    id: "lastUpdate",
    align: "right",
    icon: false,
    date: true,
    numeric: false,
    disablePadding: false,
    label: "Account Updated",
  },
  {
    id: "created",
    align: "right",
    icon: false,
    date: true,
    numeric: false,
    disablePadding: false,
    label: "Registered",
  },
  {
    id: "active",
    align: "left",
    icon: true,
    date: false,
    numeric: false,
    disablePadding: true,
    label: "Active",
  },
];
